// Generated by scripts/generate-master-catalog.py — do not hand-edit.
const GH_OWNER = 'Sreenivas-Sadhu-Prabhakara';
const CATALOG = [
 {
  "name": "Shariah Supervisory Board Directory",
  "repo": "isb-shariah-supervisory-board-directory",
  "deep": false,
  "area": "Shariah Governance and Compliance",
  "domain": "Shariah Governance",
  "pattern": "Catalog",
  "asset": "SSB Member Mandate",
  "cr": "SSB Member Mandate Directory Entry",
  "ns": "isb-governance",
  "kind": "Shariah governance (mandatory layer across every Islamic banking line)",
  "cases": [
   "Maintain SSB Member Mandate records as the authoritative Shariah-governance source",
   "Evidence Shariah compliance for products, contracts, and campaigns before launch",
   "Drive periodic Shariah audit cycles and remediation tracking",
   "Compute/route obligatory religious dues with full auditability"
  ],
  "providers": [
   "Standards: AAOIFI Shariah & accounting standards, IFSB prudential standards",
   "Screening data: Refinitiv/LSEG Islamic indices, IdealRatings",
   "SSB workflow & fatwa management tooling; zakat authorities (e.g. national boards)"
  ]
 },
 {
  "name": "Fatwa And Ruling Repository",
  "repo": "isb-fatwa-and-ruling-repository",
  "deep": false,
  "area": "Shariah Governance and Compliance",
  "domain": "Shariah Governance",
  "pattern": "Catalog",
  "asset": "Shariah Ruling",
  "cr": "Shariah Ruling Directory Entry",
  "ns": "isb-governance",
  "kind": "Shariah governance (mandatory layer across every Islamic banking line)",
  "cases": [
   "Maintain Shariah Ruling records as the authoritative Shariah-governance source",
   "Evidence Shariah compliance for products, contracts, and campaigns before launch",
   "Drive periodic Shariah audit cycles and remediation tracking",
   "Compute/route obligatory religious dues with full auditability"
  ],
  "providers": [
   "Standards: AAOIFI Shariah & accounting standards, IFSB prudential standards",
   "Screening data: Refinitiv/LSEG Islamic indices, IdealRatings",
   "SSB workflow & fatwa management tooling; zakat authorities (e.g. national boards)"
  ]
 },
 {
  "name": "Shariah Compliance Review",
  "repo": "isb-shariah-compliance-review",
  "deep": false,
  "area": "Shariah Governance and Compliance",
  "domain": "Shariah Governance",
  "pattern": "Assess",
  "asset": "Shariah Compliance Case",
  "cr": "Shariah Compliance Case Assessment",
  "ns": "isb-governance",
  "kind": "Shariah governance (mandatory layer across every Islamic banking line)",
  "cases": [
   "Maintain Shariah Compliance Case records as the authoritative Shariah-governance source",
   "Evidence Shariah compliance for products, contracts, and campaigns before launch",
   "Drive periodic Shariah audit cycles and remediation tracking",
   "Compute/route obligatory religious dues with full auditability"
  ],
  "providers": [
   "Standards: AAOIFI Shariah & accounting standards, IFSB prudential standards",
   "Screening data: Refinitiv/LSEG Islamic indices, IdealRatings",
   "SSB workflow & fatwa management tooling; zakat authorities (e.g. national boards)"
  ]
 },
 {
  "name": "Shariah Audit",
  "repo": "isb-shariah-audit",
  "deep": false,
  "area": "Shariah Governance and Compliance",
  "domain": "Shariah Governance",
  "pattern": "Assess",
  "asset": "Shariah Audit Engagement",
  "cr": "Shariah Audit Engagement Assessment",
  "ns": "isb-governance",
  "kind": "Shariah governance (mandatory layer across every Islamic banking line)",
  "cases": [
   "Maintain Shariah Audit Engagement records as the authoritative Shariah-governance source",
   "Evidence Shariah compliance for products, contracts, and campaigns before launch",
   "Drive periodic Shariah audit cycles and remediation tracking",
   "Compute/route obligatory religious dues with full auditability"
  ],
  "providers": [
   "Standards: AAOIFI Shariah & accounting standards, IFSB prudential standards",
   "Screening data: Refinitiv/LSEG Islamic indices, IdealRatings",
   "SSB workflow & fatwa management tooling; zakat authorities (e.g. national boards)"
  ]
 },
 {
  "name": "Income Purification",
  "repo": "isb-income-purification",
  "deep": false,
  "area": "Shariah Governance and Compliance",
  "domain": "Shariah Governance",
  "pattern": "Process",
  "asset": "Purification Entry",
  "cr": "Purification Entry Procedure",
  "ns": "isb-governance",
  "kind": "Shariah governance (mandatory layer across every Islamic banking line)",
  "cases": [
   "Maintain Purification Entry records as the authoritative Shariah-governance source",
   "Evidence Shariah compliance for products, contracts, and campaigns before launch",
   "Drive periodic Shariah audit cycles and remediation tracking",
   "Compute/route obligatory religious dues with full auditability"
  ],
  "providers": [
   "Standards: AAOIFI Shariah & accounting standards, IFSB prudential standards",
   "Screening data: Refinitiv/LSEG Islamic indices, IdealRatings",
   "SSB workflow & fatwa management tooling; zakat authorities (e.g. national boards)"
  ]
 },
 {
  "name": "Zakat Calculation",
  "repo": "isb-zakat-calculation",
  "deep": true,
  "area": "Shariah Governance and Compliance",
  "domain": "Shariah Governance",
  "pattern": "Process",
  "asset": "Zakat Assessment",
  "cr": "Zakat Assessment Procedure",
  "ns": "isb-governance",
  "kind": "Shariah governance (mandatory layer across every Islamic banking line)",
  "cases": [
   "Compute zakat on eligible balances at nisab thresholds for consenting customers",
   "Calculate the bank's own corporate zakat per AAOIFI methodology",
   "Generate certificates customers can use for personal religious compliance",
   "Feed Zakat Distribution with assessed amounts by category of recipient"
  ],
  "providers": [
   "Standards: AAOIFI Shariah & accounting standards, IFSB prudential standards",
   "Screening data: Refinitiv/LSEG Islamic indices, IdealRatings",
   "SSB workflow & fatwa management tooling; zakat authorities (e.g. national boards)"
  ]
 },
 {
  "name": "Zakat Distribution",
  "repo": "isb-zakat-distribution",
  "deep": false,
  "area": "Shariah Governance and Compliance",
  "domain": "Shariah Governance",
  "pattern": "Distribute",
  "asset": "Zakat Disbursement",
  "cr": "Zakat Disbursement Distribution",
  "ns": "isb-governance",
  "kind": "Shariah governance (mandatory layer across every Islamic banking line)",
  "cases": [
   "Maintain Zakat Disbursement records as the authoritative Shariah-governance source",
   "Evidence Shariah compliance for products, contracts, and campaigns before launch",
   "Drive periodic Shariah audit cycles and remediation tracking",
   "Compute/route obligatory religious dues with full auditability"
  ],
  "providers": [
   "Standards: AAOIFI Shariah & accounting standards, IFSB prudential standards",
   "Screening data: Refinitiv/LSEG Islamic indices, IdealRatings",
   "SSB workflow & fatwa management tooling; zakat authorities (e.g. national boards)"
  ]
 },
 {
  "name": "Sadaqah And Charity Management",
  "repo": "isb-sadaqah-and-charity-management",
  "deep": false,
  "area": "Shariah Governance and Compliance",
  "domain": "Shariah Governance",
  "pattern": "Manage",
  "asset": "Charity Pool",
  "cr": "Charity Pool Management Plan",
  "ns": "isb-governance",
  "kind": "Shariah governance (mandatory layer across every Islamic banking line)",
  "cases": [
   "Maintain Charity Pool records as the authoritative Shariah-governance source",
   "Evidence Shariah compliance for products, contracts, and campaigns before launch",
   "Drive periodic Shariah audit cycles and remediation tracking",
   "Compute/route obligatory religious dues with full auditability"
  ],
  "providers": [
   "Standards: AAOIFI Shariah & accounting standards, IFSB prudential standards",
   "Screening data: Refinitiv/LSEG Islamic indices, IdealRatings",
   "SSB workflow & fatwa management tooling; zakat authorities (e.g. national boards)"
  ]
 },
 {
  "name": "Wadiah Safekeeping Account",
  "repo": "isb-wadiah-safekeeping-account",
  "deep": false,
  "area": "Deposits and Investment Accounts",
  "domain": "Islamic Deposits",
  "pattern": "Fulfill",
  "asset": "Wadiah Custody Account",
  "cr": "Wadiah Custody Account Fulfillment Arrangement",
  "ns": "isb-deposits",
  "kind": "Islamic retail banking (deposits \u2014 non-interest-bearing by construction)",
  "cases": [
   "Open and service Wadiah Custody Account records under the correct contract (Wadiah/Qard/Mudarabah/Wakala)",
   "Gate activation on KYC + Shariah screening outcomes",
   "Attribute investment-account balances to profit-sharing pools (no interest accrual, ever)",
   "Stream postings to financial-crime monitoring"
  ],
  "providers": [
   "Islamic cores: Azentio iMAL, Oracle FLEXCUBE Islamic, Temenos Islamic Banking, ICS BANKS Islamic",
   "Profit-distribution engines; AAOIFI-aligned GL",
   "Channels: any conventional digital-banking front-end (the contract is the boundary)"
  ]
 },
 {
  "name": "Qard Hassan Account",
  "repo": "isb-qard-hassan-account",
  "deep": false,
  "area": "Deposits and Investment Accounts",
  "domain": "Islamic Deposits",
  "pattern": "Fulfill",
  "asset": "Qard Hassan Account",
  "cr": "Qard Hassan Account Fulfillment Arrangement",
  "ns": "isb-deposits",
  "kind": "Islamic retail banking (deposits \u2014 non-interest-bearing by construction)",
  "cases": [
   "Open and service Qard Hassan Account records under the correct contract (Wadiah/Qard/Mudarabah/Wakala)",
   "Gate activation on KYC + Shariah screening outcomes",
   "Attribute investment-account balances to profit-sharing pools (no interest accrual, ever)",
   "Stream postings to financial-crime monitoring"
  ],
  "providers": [
   "Islamic cores: Azentio iMAL, Oracle FLEXCUBE Islamic, Temenos Islamic Banking, ICS BANKS Islamic",
   "Profit-distribution engines; AAOIFI-aligned GL",
   "Channels: any conventional digital-banking front-end (the contract is the boundary)"
  ]
 },
 {
  "name": "Mudarabah Savings Account",
  "repo": "isb-mudarabah-savings-account",
  "deep": true,
  "area": "Deposits and Investment Accounts",
  "domain": "Islamic Deposits",
  "pattern": "Fulfill",
  "asset": "Mudarabah Savings Account",
  "cr": "Mudarabah Savings Account Fulfillment Arrangement",
  "ns": "isb-deposits",
  "kind": "Islamic retail banking (deposits \u2014 non-interest-bearing by construction)",
  "cases": [
   "Offer savings where returns come from actual pool profits, not promised interest",
   "Attribute each account's balance-days to the Mudarabah pool for profit distribution",
   "Disclose the bank's Mudarib share and historical profit rates transparently",
   "Bear pool losses by capital (account holders) unless operator negligence \u2014 as Shariah requires"
  ],
  "providers": [
   "Islamic cores: Azentio iMAL, Oracle FLEXCUBE Islamic, Temenos Islamic Banking, ICS BANKS Islamic",
   "Profit-distribution engines; AAOIFI-aligned GL",
   "Channels: any conventional digital-banking front-end (the contract is the boundary)"
  ]
 },
 {
  "name": "Mudarabah Term Investment Account",
  "repo": "isb-mudarabah-term-investment-account",
  "deep": false,
  "area": "Deposits and Investment Accounts",
  "domain": "Islamic Deposits",
  "pattern": "Fulfill",
  "asset": "Mudarabah Investment Account",
  "cr": "Mudarabah Investment Account Fulfillment Arrangement",
  "ns": "isb-deposits",
  "kind": "Islamic retail banking (deposits \u2014 non-interest-bearing by construction)",
  "cases": [
   "Open and service Mudarabah Investment Account records under the correct contract (Wadiah/Qard/Mudarabah/Wakala)",
   "Gate activation on KYC + Shariah screening outcomes",
   "Attribute investment-account balances to profit-sharing pools (no interest accrual, ever)",
   "Stream postings to financial-crime monitoring"
  ],
  "providers": [
   "Islamic cores: Azentio iMAL, Oracle FLEXCUBE Islamic, Temenos Islamic Banking, ICS BANKS Islamic",
   "Profit-distribution engines; AAOIFI-aligned GL",
   "Channels: any conventional digital-banking front-end (the contract is the boundary)"
  ]
 },
 {
  "name": "Wakala Investment Account",
  "repo": "isb-wakala-investment-account",
  "deep": false,
  "area": "Deposits and Investment Accounts",
  "domain": "Islamic Deposits",
  "pattern": "Fulfill",
  "asset": "Wakala Investment Account",
  "cr": "Wakala Investment Account Fulfillment Arrangement",
  "ns": "isb-deposits",
  "kind": "Islamic retail banking (deposits \u2014 non-interest-bearing by construction)",
  "cases": [
   "Open and service Wakala Investment Account records under the correct contract (Wadiah/Qard/Mudarabah/Wakala)",
   "Gate activation on KYC + Shariah screening outcomes",
   "Attribute investment-account balances to profit-sharing pools (no interest accrual, ever)",
   "Stream postings to financial-crime monitoring"
  ],
  "providers": [
   "Islamic cores: Azentio iMAL, Oracle FLEXCUBE Islamic, Temenos Islamic Banking, ICS BANKS Islamic",
   "Profit-distribution engines; AAOIFI-aligned GL",
   "Channels: any conventional digital-banking front-end (the contract is the boundary)"
  ]
 },
 {
  "name": "Profit Calculation And Distribution",
  "repo": "isb-profit-calculation-and-distribution",
  "deep": true,
  "area": "Deposits and Investment Accounts",
  "domain": "Profit Management",
  "pattern": "Process",
  "asset": "Profit Distribution Run",
  "cr": "Profit Distribution Run Procedure",
  "ns": "isb-deposits",
  "kind": "Islamic retail & treasury (the profit-sharing engine that replaces interest)",
  "cases": [
   "Run month-end distribution: pool income \u2192 weighted balances \u2192 Mudarib share \u2192 holder credits",
   "Apply Profit Equalization Reserve smoothing with AAOIFI-compliant disclosure",
   "Publish calculation lineage for SSB review and customer queries",
   "Re-run hypothetical scenarios before changing weightings or fees"
  ],
  "providers": [
   "Islamic core profit engines (iMAL, FLEXCUBE Islamic)",
   "AAOIFI FAS-aligned accounting; actuarial/reserve tooling"
  ]
 },
 {
  "name": "Profit Equalization Reserve",
  "repo": "isb-profit-equalization-reserve",
  "deep": false,
  "area": "Deposits and Investment Accounts",
  "domain": "Profit Management",
  "pattern": "Manage",
  "asset": "Profit Equalization Reserve",
  "cr": "Profit Equalization Reserve Management Plan",
  "ns": "isb-deposits",
  "kind": "Islamic retail & treasury (the profit-sharing engine that replaces interest)",
  "cases": [
   "Run periodic Profit Equalization Reserve cycles: pool income \u2192 weightings \u2192 Mudarib share \u2192 account holders",
   "Smooth returns across periods via reserves (PER/IRR) with full disclosure",
   "Publish profit rates to channels and regulators with calculation lineage"
  ],
  "providers": [
   "Islamic core profit engines (iMAL, FLEXCUBE Islamic)",
   "AAOIFI FAS-aligned accounting; actuarial/reserve tooling"
  ]
 },
 {
  "name": "Investment Risk Reserve",
  "repo": "isb-investment-risk-reserve",
  "deep": false,
  "area": "Deposits and Investment Accounts",
  "domain": "Profit Management",
  "pattern": "Manage",
  "asset": "Investment Risk Reserve",
  "cr": "Investment Risk Reserve Management Plan",
  "ns": "isb-deposits",
  "kind": "Islamic retail & treasury (the profit-sharing engine that replaces interest)",
  "cases": [
   "Run periodic Investment Risk Reserve cycles: pool income \u2192 weightings \u2192 Mudarib share \u2192 account holders",
   "Smooth returns across periods via reserves (PER/IRR) with full disclosure",
   "Publish profit rates to channels and regulators with calculation lineage"
  ],
  "providers": [
   "Islamic core profit engines (iMAL, FLEXCUBE Islamic)",
   "AAOIFI FAS-aligned accounting; actuarial/reserve tooling"
  ]
 },
 {
  "name": "Hibah Discretionary Gift",
  "repo": "isb-hibah-discretionary-gift",
  "deep": false,
  "area": "Deposits and Investment Accounts",
  "domain": "Profit Management",
  "pattern": "Process",
  "asset": "Hibah Award",
  "cr": "Hibah Award Procedure",
  "ns": "isb-deposits",
  "kind": "Islamic retail & treasury (the profit-sharing engine that replaces interest)",
  "cases": [
   "Run periodic Hibah Award cycles: pool income \u2192 weightings \u2192 Mudarib share \u2192 account holders",
   "Smooth returns across periods via reserves (PER/IRR) with full disclosure",
   "Publish profit rates to channels and regulators with calculation lineage"
  ],
  "providers": [
   "Islamic core profit engines (iMAL, FLEXCUBE Islamic)",
   "AAOIFI FAS-aligned accounting; actuarial/reserve tooling"
  ]
 },
 {
  "name": "Murabaha Financing",
  "repo": "isb-murabaha-financing",
  "deep": true,
  "area": "Islamic Financing",
  "domain": "Sale Based Financing",
  "pattern": "Fulfill",
  "asset": "Murabaha Facility",
  "cr": "Murabaha Facility Fulfillment Arrangement",
  "ns": "isb-financing",
  "kind": "Islamic retail & corporate financing (sale/cost-plus structures)",
  "cases": [
   "Finance vehicles/equipment/homes: bank buys the asset, sells to the customer at disclosed cost-plus markup",
   "Fix the total deferred price at contract signing \u2014 installments never recalculate like interest",
   "Evidence the bank's ownership moment (constructive possession) for Shariah audit",
   "Route any late-payment charges to the charity pool, never to income"
  ],
  "providers": [
   "Commodity platforms: Bursa Suq Al-Sila', DDCAP ETHOS (for Tawarruq)",
   "Islamic LOS modules (iMAL, FLEXCUBE Islamic, Temenos)",
   "Asset registries, valuers, and supplier networks (the bank actually buys the asset)"
  ]
 },
 {
  "name": "Commodity Murabaha Tawarruq",
  "repo": "isb-commodity-murabaha-tawarruq",
  "deep": false,
  "area": "Islamic Financing",
  "domain": "Sale Based Financing",
  "pattern": "Process",
  "asset": "Tawarruq Transaction",
  "cr": "Tawarruq Transaction Procedure",
  "ns": "isb-financing",
  "kind": "Islamic retail & corporate financing (sale/cost-plus structures)",
  "cases": [
   "Originate Tawarruq Transaction deals: asset purchase \u2192 markup disclosure \u2192 deferred-sale to customer",
   "Execute commodity legs with brokers and evidence constructive possession",
   "Service installment schedules where the markup is fixed at contract (never recalculated as interest)",
   "Route late-payment amounts to charity, not income (Shariah requirement)"
  ],
  "providers": [
   "Commodity platforms: Bursa Suq Al-Sila', DDCAP ETHOS (for Tawarruq)",
   "Islamic LOS modules (iMAL, FLEXCUBE Islamic, Temenos)",
   "Asset registries, valuers, and supplier networks (the bank actually buys the asset)"
  ]
 },
 {
  "name": "Istisna Construction Financing",
  "repo": "isb-istisna-construction-financing",
  "deep": false,
  "area": "Islamic Financing",
  "domain": "Sale Based Financing",
  "pattern": "Fulfill",
  "asset": "Istisna Facility",
  "cr": "Istisna Facility Fulfillment Arrangement",
  "ns": "isb-financing",
  "kind": "Islamic retail & corporate financing (sale/cost-plus structures)",
  "cases": [
   "Originate Istisna Facility deals: asset purchase \u2192 markup disclosure \u2192 deferred-sale to customer",
   "Execute commodity legs with brokers and evidence constructive possession",
   "Service installment schedules where the markup is fixed at contract (never recalculated as interest)",
   "Route late-payment amounts to charity, not income (Shariah requirement)"
  ],
  "providers": [
   "Commodity platforms: Bursa Suq Al-Sila', DDCAP ETHOS (for Tawarruq)",
   "Islamic LOS modules (iMAL, FLEXCUBE Islamic, Temenos)",
   "Asset registries, valuers, and supplier networks (the bank actually buys the asset)"
  ]
 },
 {
  "name": "Salam Commodity Forward",
  "repo": "isb-salam-commodity-forward",
  "deep": false,
  "area": "Islamic Financing",
  "domain": "Sale Based Financing",
  "pattern": "Fulfill",
  "asset": "Salam Contract",
  "cr": "Salam Contract Fulfillment Arrangement",
  "ns": "isb-financing",
  "kind": "Islamic retail & corporate financing (sale/cost-plus structures)",
  "cases": [
   "Originate Salam Contract deals: asset purchase \u2192 markup disclosure \u2192 deferred-sale to customer",
   "Execute commodity legs with brokers and evidence constructive possession",
   "Service installment schedules where the markup is fixed at contract (never recalculated as interest)",
   "Route late-payment amounts to charity, not income (Shariah requirement)"
  ],
  "providers": [
   "Commodity platforms: Bursa Suq Al-Sila', DDCAP ETHOS (for Tawarruq)",
   "Islamic LOS modules (iMAL, FLEXCUBE Islamic, Temenos)",
   "Asset registries, valuers, and supplier networks (the bank actually buys the asset)"
  ]
 },
 {
  "name": "Asset Acquisition Agency",
  "repo": "isb-asset-acquisition-agency",
  "deep": false,
  "area": "Islamic Financing",
  "domain": "Sale Based Financing",
  "pattern": "Process",
  "asset": "Wakala Purchase Mandate",
  "cr": "Wakala Purchase Mandate Procedure",
  "ns": "isb-financing",
  "kind": "Islamic retail & corporate financing (sale/cost-plus structures)",
  "cases": [
   "Originate Wakala Purchase Mandate deals: asset purchase \u2192 markup disclosure \u2192 deferred-sale to customer",
   "Execute commodity legs with brokers and evidence constructive possession",
   "Service installment schedules where the markup is fixed at contract (never recalculated as interest)",
   "Route late-payment amounts to charity, not income (Shariah requirement)"
  ],
  "providers": [
   "Commodity platforms: Bursa Suq Al-Sila', DDCAP ETHOS (for Tawarruq)",
   "Islamic LOS modules (iMAL, FLEXCUBE Islamic, Temenos)",
   "Asset registries, valuers, and supplier networks (the bank actually buys the asset)"
  ]
 },
 {
  "name": "Ijara Leasing",
  "repo": "isb-ijara-leasing",
  "deep": false,
  "area": "Islamic Financing",
  "domain": "Lease And Partnership Financing",
  "pattern": "Fulfill",
  "asset": "Ijara Lease",
  "cr": "Ijara Lease Fulfillment Arrangement",
  "ns": "isb-financing",
  "kind": "Islamic retail & corporate financing (lease/equity structures)",
  "cases": [
   "Operate Ijara Lease arrangements with bank ownership reflected for the lease/partnership term",
   "Adjust rentals/units as ownership diminishes (Diminishing Musharakah) with transparent schedules",
   "Share venture outcomes by pre-agreed ratios \u2014 losses borne by capital, not penalized (Mudarabah/Musharakah)",
   "Handle maintenance/takaful obligations that follow ownership, not the customer"
  ],
  "providers": [
   "Islamic cores + leasing modules; land/vehicle registries",
   "Takaful providers (asset coverage is typically mandatory)",
   "Property valuers; co-ownership accounting"
  ]
 },
 {
  "name": "Ijara Muntahia Bittamleek",
  "repo": "isb-ijara-muntahia-bittamleek",
  "deep": false,
  "area": "Islamic Financing",
  "domain": "Lease And Partnership Financing",
  "pattern": "Fulfill",
  "asset": "Lease To Own Arrangement",
  "cr": "Lease To Own Arrangement Fulfillment Arrangement",
  "ns": "isb-financing",
  "kind": "Islamic retail & corporate financing (lease/equity structures)",
  "cases": [
   "Operate Lease To Own Arrangement arrangements with bank ownership reflected for the lease/partnership term",
   "Adjust rentals/units as ownership diminishes (Diminishing Musharakah) with transparent schedules",
   "Share venture outcomes by pre-agreed ratios \u2014 losses borne by capital, not penalized (Mudarabah/Musharakah)",
   "Handle maintenance/takaful obligations that follow ownership, not the customer"
  ],
  "providers": [
   "Islamic cores + leasing modules; land/vehicle registries",
   "Takaful providers (asset coverage is typically mandatory)",
   "Property valuers; co-ownership accounting"
  ]
 },
 {
  "name": "Diminishing Musharakah Home Finance",
  "repo": "isb-diminishing-musharakah-home-finance",
  "deep": false,
  "area": "Islamic Financing",
  "domain": "Lease And Partnership Financing",
  "pattern": "Fulfill",
  "asset": "Diminishing Musharakah Facility",
  "cr": "Diminishing Musharakah Facility Fulfillment Arrangement",
  "ns": "isb-financing",
  "kind": "Islamic retail & corporate financing (lease/equity structures)",
  "cases": [
   "Operate Diminishing Musharakah Facility arrangements with bank ownership reflected for the lease/partnership term",
   "Adjust rentals/units as ownership diminishes (Diminishing Musharakah) with transparent schedules",
   "Share venture outcomes by pre-agreed ratios \u2014 losses borne by capital, not penalized (Mudarabah/Musharakah)",
   "Handle maintenance/takaful obligations that follow ownership, not the customer"
  ],
  "providers": [
   "Islamic cores + leasing modules; land/vehicle registries",
   "Takaful providers (asset coverage is typically mandatory)",
   "Property valuers; co-ownership accounting"
  ]
 },
 {
  "name": "Musharakah Partnership Financing",
  "repo": "isb-musharakah-partnership-financing",
  "deep": false,
  "area": "Islamic Financing",
  "domain": "Lease And Partnership Financing",
  "pattern": "Fulfill",
  "asset": "Musharakah Facility",
  "cr": "Musharakah Facility Fulfillment Arrangement",
  "ns": "isb-financing",
  "kind": "Islamic retail & corporate financing (lease/equity structures)",
  "cases": [
   "Operate Musharakah Facility arrangements with bank ownership reflected for the lease/partnership term",
   "Adjust rentals/units as ownership diminishes (Diminishing Musharakah) with transparent schedules",
   "Share venture outcomes by pre-agreed ratios \u2014 losses borne by capital, not penalized (Mudarabah/Musharakah)",
   "Handle maintenance/takaful obligations that follow ownership, not the customer"
  ],
  "providers": [
   "Islamic cores + leasing modules; land/vehicle registries",
   "Takaful providers (asset coverage is typically mandatory)",
   "Property valuers; co-ownership accounting"
  ]
 },
 {
  "name": "Mudarabah Venture Financing",
  "repo": "isb-mudarabah-venture-financing",
  "deep": false,
  "area": "Islamic Financing",
  "domain": "Lease And Partnership Financing",
  "pattern": "Fulfill",
  "asset": "Mudarabah Facility",
  "cr": "Mudarabah Facility Fulfillment Arrangement",
  "ns": "isb-financing",
  "kind": "Islamic retail & corporate financing (lease/equity structures)",
  "cases": [
   "Operate Mudarabah Facility arrangements with bank ownership reflected for the lease/partnership term",
   "Adjust rentals/units as ownership diminishes (Diminishing Musharakah) with transparent schedules",
   "Share venture outcomes by pre-agreed ratios \u2014 losses borne by capital, not penalized (Mudarabah/Musharakah)",
   "Handle maintenance/takaful obligations that follow ownership, not the customer"
  ],
  "providers": [
   "Islamic cores + leasing modules; land/vehicle registries",
   "Takaful providers (asset coverage is typically mandatory)",
   "Property valuers; co-ownership accounting"
  ]
 },
 {
  "name": "Qard Hassan Benevolent Loan",
  "repo": "isb-qard-hassan-benevolent-loan",
  "deep": false,
  "area": "Islamic Financing",
  "domain": "Lease And Partnership Financing",
  "pattern": "Fulfill",
  "asset": "Qard Hassan Facility",
  "cr": "Qard Hassan Facility Fulfillment Arrangement",
  "ns": "isb-financing",
  "kind": "Islamic retail & corporate financing (lease/equity structures)",
  "cases": [
   "Operate Qard Hassan Facility arrangements with bank ownership reflected for the lease/partnership term",
   "Adjust rentals/units as ownership diminishes (Diminishing Musharakah) with transparent schedules",
   "Share venture outcomes by pre-agreed ratios \u2014 losses borne by capital, not penalized (Mudarabah/Musharakah)",
   "Handle maintenance/takaful obligations that follow ownership, not the customer"
  ],
  "providers": [
   "Islamic cores + leasing modules; land/vehicle registries",
   "Takaful providers (asset coverage is typically mandatory)",
   "Property valuers; co-ownership accounting"
  ]
 },
 {
  "name": "Late Payment Charity Handling",
  "repo": "isb-late-payment-charity-handling",
  "deep": false,
  "area": "Islamic Financing",
  "domain": "Lease And Partnership Financing",
  "pattern": "Process",
  "asset": "Late Payment Charity Entry",
  "cr": "Late Payment Charity Entry Procedure",
  "ns": "isb-financing",
  "kind": "Islamic retail & corporate financing (lease/equity structures)",
  "cases": [
   "Operate Late Payment Charity Entry arrangements with bank ownership reflected for the lease/partnership term",
   "Adjust rentals/units as ownership diminishes (Diminishing Musharakah) with transparent schedules",
   "Share venture outcomes by pre-agreed ratios \u2014 losses borne by capital, not penalized (Mudarabah/Musharakah)",
   "Handle maintenance/takaful obligations that follow ownership, not the customer"
  ],
  "providers": [
   "Islamic cores + leasing modules; land/vehicle registries",
   "Takaful providers (asset coverage is typically mandatory)",
   "Property valuers; co-ownership accounting"
  ]
 },
 {
  "name": "Sukuk Issuance",
  "repo": "isb-sukuk-issuance",
  "deep": true,
  "area": "Treasury Markets and Sukuk",
  "domain": "Sukuk",
  "pattern": "Process",
  "asset": "Sukuk Issuance Program",
  "cr": "Sukuk Issuance Program Procedure",
  "ns": "isb-treasury",
  "kind": "Islamic capital markets & treasury",
  "cases": [
   "Structure asset-backed/asset-based programs (Ijara, Murabaha, Wakala sukuk) with SSB sign-off evidence",
   "Manage bookbuilding, allocation, and settlement with paying agents and CSDs",
   "Track underlying-asset performance that drives periodic distributions",
   "Handle dissolution and redemption at maturity or trigger events"
  ],
  "providers": [
   "Standards: AAOIFI Sukuk standards, IIFM documentation",
   "CSDs/ICSDs: Euroclear/Clearstream, national CSDs; paying agents",
   "Listing venues (Nasdaq Dubai, Bursa Malaysia); Bloomberg/IdealRatings Sukuk data"
  ]
 },
 {
  "name": "Sukuk Registry And Custody",
  "repo": "isb-sukuk-registry-and-custody",
  "deep": false,
  "area": "Treasury Markets and Sukuk",
  "domain": "Sukuk",
  "pattern": "Administer",
  "asset": "Sukuk Holding",
  "cr": "Sukuk Holding Administrative Plan",
  "ns": "isb-treasury",
  "kind": "Islamic capital markets & treasury",
  "cases": [
   "Structure and issue Sukuk Holding programs with underlying-asset linkage evidenced",
   "Maintain holdings, periodic distributions, and dissolution events",
   "Manage portfolios for HQLA/liquidity purposes under IFSB rules"
  ],
  "providers": [
   "Standards: AAOIFI Sukuk standards, IIFM documentation",
   "CSDs/ICSDs: Euroclear/Clearstream, national CSDs; paying agents",
   "Listing venues (Nasdaq Dubai, Bursa Malaysia); Bloomberg/IdealRatings Sukuk data"
  ]
 },
 {
  "name": "Sukuk Portfolio Management",
  "repo": "isb-sukuk-portfolio-management",
  "deep": false,
  "area": "Treasury Markets and Sukuk",
  "domain": "Sukuk",
  "pattern": "Manage",
  "asset": "Sukuk Portfolio",
  "cr": "Sukuk Portfolio Management Plan",
  "ns": "isb-treasury",
  "kind": "Islamic capital markets & treasury",
  "cases": [
   "Structure and issue Sukuk Portfolio programs with underlying-asset linkage evidenced",
   "Maintain holdings, periodic distributions, and dissolution events",
   "Manage portfolios for HQLA/liquidity purposes under IFSB rules"
  ],
  "providers": [
   "Standards: AAOIFI Sukuk standards, IIFM documentation",
   "CSDs/ICSDs: Euroclear/Clearstream, national CSDs; paying agents",
   "Listing venues (Nasdaq Dubai, Bursa Malaysia); Bloomberg/IdealRatings Sukuk data"
  ]
 },
 {
  "name": "Interbank Commodity Murabaha Desk",
  "repo": "isb-interbank-commodity-murabaha-desk",
  "deep": false,
  "area": "Treasury Markets and Sukuk",
  "domain": "Islamic Treasury",
  "pattern": "Operate",
  "asset": "Interbank Murabaha Deal",
  "cr": "Interbank Murabaha Deal Operating Session",
  "ns": "isb-treasury",
  "kind": "Islamic treasury & markets (interest-free liquidity and hedging)",
  "cases": [
   "Place/accept interbank liquidity via Interbank Murabaha Deal structures instead of interest-bearing deposits",
   "Hedge FX exposure with unilateral promise (Wa'd) constructs documented per IIFM",
   "Screen instruments/equities for Shariah eligibility before treasury investment"
  ],
  "providers": [
   "Interbank: commodity Murabaha counterparties via Bursa Suq Al-Sila'/DDCAP",
   "IIFM/ISDA Tahawwut master agreements (Wa'd-based hedging)",
   "Central-bank Islamic facilities; Murex/Calypso Islamic configurations"
  ]
 },
 {
  "name": "Islamic FX Wad Arrangements",
  "repo": "isb-islamic-fx-wad-arrangements",
  "deep": false,
  "area": "Treasury Markets and Sukuk",
  "domain": "Islamic Treasury",
  "pattern": "Process",
  "asset": "Wad FX Arrangement",
  "cr": "Wad FX Arrangement Procedure",
  "ns": "isb-treasury",
  "kind": "Islamic treasury & markets (interest-free liquidity and hedging)",
  "cases": [
   "Place/accept interbank liquidity via Wad FX Arrangement structures instead of interest-bearing deposits",
   "Hedge FX exposure with unilateral promise (Wa'd) constructs documented per IIFM",
   "Screen instruments/equities for Shariah eligibility before treasury investment"
  ],
  "providers": [
   "Interbank: commodity Murabaha counterparties via Bursa Suq Al-Sila'/DDCAP",
   "IIFM/ISDA Tahawwut master agreements (Wa'd-based hedging)",
   "Central-bank Islamic facilities; Murex/Calypso Islamic configurations"
  ]
 },
 {
  "name": "Shariah Compliant Liquidity Management",
  "repo": "isb-shariah-compliant-liquidity-management",
  "deep": false,
  "area": "Treasury Markets and Sukuk",
  "domain": "Islamic Treasury",
  "pattern": "Manage",
  "asset": "Liquidity Position",
  "cr": "Liquidity Position Management Plan",
  "ns": "isb-treasury",
  "kind": "Islamic treasury & markets (interest-free liquidity and hedging)",
  "cases": [
   "Place/accept interbank liquidity via Liquidity Position structures instead of interest-bearing deposits",
   "Hedge FX exposure with unilateral promise (Wa'd) constructs documented per IIFM",
   "Screen instruments/equities for Shariah eligibility before treasury investment"
  ],
  "providers": [
   "Interbank: commodity Murabaha counterparties via Bursa Suq Al-Sila'/DDCAP",
   "IIFM/ISDA Tahawwut master agreements (Wa'd-based hedging)",
   "Central-bank Islamic facilities; Murex/Calypso Islamic configurations"
  ]
 },
 {
  "name": "Halal Equity Screening",
  "repo": "isb-halal-equity-screening",
  "deep": false,
  "area": "Treasury Markets and Sukuk",
  "domain": "Islamic Treasury",
  "pattern": "Assess",
  "asset": "Equity Screening Result",
  "cr": "Equity Screening Result Assessment",
  "ns": "isb-treasury",
  "kind": "Islamic treasury & markets (interest-free liquidity and hedging)",
  "cases": [
   "Place/accept interbank liquidity via Equity Screening Result structures instead of interest-bearing deposits",
   "Hedge FX exposure with unilateral promise (Wa'd) constructs documented per IIFM",
   "Screen instruments/equities for Shariah eligibility before treasury investment"
  ],
  "providers": [
   "Interbank: commodity Murabaha counterparties via Bursa Suq Al-Sila'/DDCAP",
   "IIFM/ISDA Tahawwut master agreements (Wa'd-based hedging)",
   "Central-bank Islamic facilities; Murex/Calypso Islamic configurations"
  ]
 },
 {
  "name": "Takaful Policy Administration",
  "repo": "isb-takaful-policy-administration",
  "deep": false,
  "area": "Takaful and Shared Operations",
  "domain": "Takaful",
  "pattern": "Administer",
  "asset": "Takaful Certificate",
  "cr": "Takaful Certificate Administrative Plan",
  "ns": "isb-operations",
  "kind": "Takaful (Islamic cooperative insurance)",
  "cases": [
   "Administer Takaful Certificate records under Wakala/Mudarabah operator models",
   "Process claims from the participants' risk pool with surplus-sharing rules",
   "Arrange retakaful capacity treaty-by-treaty"
  ],
  "providers": [
   "Takaful cores: Azentio, Beyontec; retakaful: Hannover ReTakaful, Malaysian Re",
   "AAOIFI FAS for Takaful accounting; actuarial platforms"
  ]
 },
 {
  "name": "Takaful Claims Processing",
  "repo": "isb-takaful-claims-processing",
  "deep": true,
  "area": "Takaful and Shared Operations",
  "domain": "Takaful",
  "pattern": "Process",
  "asset": "Takaful Claim",
  "cr": "Takaful Claim Procedure",
  "ns": "isb-operations",
  "kind": "Takaful (Islamic cooperative insurance)",
  "cases": [
   "Process claims as payouts from the participants' mutual pool, not the operator's P&L",
   "Apply Wakala-fee/surplus rules between operator and pool on every settlement",
   "Coordinate retakaful recoveries on large claims",
   "Distribute pool surplus back to participants per the certificate terms"
  ],
  "providers": [
   "Takaful cores: Azentio, Beyontec; retakaful: Hannover ReTakaful, Malaysian Re",
   "AAOIFI FAS for Takaful accounting; actuarial platforms"
  ]
 },
 {
  "name": "Retakaful Arrangement",
  "repo": "isb-retakaful-arrangement",
  "deep": false,
  "area": "Takaful and Shared Operations",
  "domain": "Takaful",
  "pattern": "Manage",
  "asset": "Retakaful Treaty",
  "cr": "Retakaful Treaty Management Plan",
  "ns": "isb-operations",
  "kind": "Takaful (Islamic cooperative insurance)",
  "cases": [
   "Administer Retakaful Treaty records under Wakala/Mudarabah operator models",
   "Process claims from the participants' risk pool with surplus-sharing rules",
   "Arrange retakaful capacity treaty-by-treaty"
  ],
  "providers": [
   "Takaful cores: Azentio, Beyontec; retakaful: Hannover ReTakaful, Malaysian Re",
   "AAOIFI FAS for Takaful accounting; actuarial platforms"
  ]
 },
 {
  "name": "Ujrah Card Services",
  "repo": "isb-ujrah-card-services",
  "deep": false,
  "area": "Takaful and Shared Operations",
  "domain": "Islamic Cards and Payments",
  "pattern": "Fulfill",
  "asset": "Ujrah Card Facility",
  "cr": "Ujrah Card Facility Fulfillment Arrangement",
  "ns": "isb-operations",
  "kind": "Islamic retail payments & cards (fee-based, riba-free)",
  "cases": [
   "Issue and service Ujrah Card Facility products on fee (Ujrah) structures \u2014 no revolving interest",
   "Validate, route, and execute payment instructions with debit/credit atomicity",
   "Charge late amounts to charity pools per Shariah board rulings"
  ],
  "providers": [
   "Networks: Visa/Mastercard (Ujrah/fee-based card programs), local schemes",
   "Rails (halal-neutral): SWIFT, SEPA, UPI/NPCI, instant-payment systems",
   "Processors with Islamic product configs (M2P, Marqeta)"
  ]
 },
 {
  "name": "Payment Order",
  "repo": "isb-payment-order",
  "deep": false,
  "area": "Takaful and Shared Operations",
  "domain": "Islamic Cards and Payments",
  "pattern": "Process",
  "asset": "Payment Order",
  "cr": "Payment Order Procedure",
  "ns": "isb-operations",
  "kind": "Islamic retail payments & cards (fee-based, riba-free)",
  "cases": [
   "Issue and service Payment Order products on fee (Ujrah) structures \u2014 no revolving interest",
   "Validate, route, and execute payment instructions with debit/credit atomicity",
   "Charge late amounts to charity pools per Shariah board rulings"
  ],
  "providers": [
   "Networks: Visa/Mastercard (Ujrah/fee-based card programs), local schemes",
   "Rails (halal-neutral): SWIFT, SEPA, UPI/NPCI, instant-payment systems",
   "Processors with Islamic product configs (M2P, Marqeta)"
  ]
 },
 {
  "name": "Payment Execution",
  "repo": "isb-payment-execution",
  "deep": false,
  "area": "Takaful and Shared Operations",
  "domain": "Islamic Cards and Payments",
  "pattern": "Process",
  "asset": "Payment Transaction",
  "cr": "Payment Transaction Procedure",
  "ns": "isb-operations",
  "kind": "Islamic retail payments & cards (fee-based, riba-free)",
  "cases": [
   "Issue and service Payment Transaction products on fee (Ujrah) structures \u2014 no revolving interest",
   "Validate, route, and execute payment instructions with debit/credit atomicity",
   "Charge late amounts to charity pools per Shariah board rulings"
  ],
  "providers": [
   "Networks: Visa/Mastercard (Ujrah/fee-based card programs), local schemes",
   "Rails (halal-neutral): SWIFT, SEPA, UPI/NPCI, instant-payment systems",
   "Processors with Islamic product configs (M2P, Marqeta)"
  ]
 },
 {
  "name": "Customer Reference Data",
  "repo": "isb-customer-reference-data",
  "deep": false,
  "area": "Takaful and Shared Operations",
  "domain": "Shared Operations",
  "pattern": "Maintain",
  "asset": "Customer Reference Data",
  "cr": "Customer Reference Data Maintenance Agreement",
  "ns": "isb-operations",
  "kind": "Universal Islamic banking operations & compliance",
  "cases": [
   "Maintain Customer Reference Data records consistently across the Islamic estate",
   "Combine conventional KYC/AML with Shariah-specific screening at onboarding",
   "Produce AAOIFI-basis financials and IFSB regulatory returns",
   "Operate branch/digital channels with products labeled by underlying contract"
  ],
  "providers": [
   "AML/screening: NICE Actimize, World-Check (plus Shariah screening data)",
   "Accounting: AAOIFI FAS-aligned GL mappings on SAP/Oracle",
   "Regulators: IFSB-aligned returns; national central banks"
  ]
 },
 {
  "name": "KYC And Shariah Screening",
  "repo": "isb-kyc-and-shariah-screening",
  "deep": false,
  "area": "Takaful and Shared Operations",
  "domain": "Shared Operations",
  "pattern": "Process",
  "asset": "KYC Shariah Assessment",
  "cr": "KYC Shariah Assessment Procedure",
  "ns": "isb-operations",
  "kind": "Universal Islamic banking operations & compliance",
  "cases": [
   "Maintain KYC Shariah Assessment records consistently across the Islamic estate",
   "Combine conventional KYC/AML with Shariah-specific screening at onboarding",
   "Produce AAOIFI-basis financials and IFSB regulatory returns",
   "Operate branch/digital channels with products labeled by underlying contract"
  ],
  "providers": [
   "AML/screening: NICE Actimize, World-Check (plus Shariah screening data)",
   "Accounting: AAOIFI FAS-aligned GL mappings on SAP/Oracle",
   "Regulators: IFSB-aligned returns; national central banks"
  ]
 },
 {
  "name": "Financial Crime Monitoring",
  "repo": "isb-financial-crime-monitoring",
  "deep": false,
  "area": "Takaful and Shared Operations",
  "domain": "Shared Operations",
  "pattern": "Monitor",
  "asset": "Financial Crime Alert",
  "cr": "Financial Crime Alert Monitoring State",
  "ns": "isb-operations",
  "kind": "Universal Islamic banking operations & compliance",
  "cases": [
   "Maintain Financial Crime Alert records consistently across the Islamic estate",
   "Combine conventional KYC/AML with Shariah-specific screening at onboarding",
   "Produce AAOIFI-basis financials and IFSB regulatory returns",
   "Operate branch/digital channels with products labeled by underlying contract"
  ],
  "providers": [
   "AML/screening: NICE Actimize, World-Check (plus Shariah screening data)",
   "Accounting: AAOIFI FAS-aligned GL mappings on SAP/Oracle",
   "Regulators: IFSB-aligned returns; national central banks"
  ]
 },
 {
  "name": "AAOIFI Financial Accounting",
  "repo": "isb-aaoifi-financial-accounting",
  "deep": false,
  "area": "Takaful and Shared Operations",
  "domain": "Shared Operations",
  "pattern": "Process",
  "asset": "AAOIFI Ledger Posting",
  "cr": "AAOIFI Ledger Posting Procedure",
  "ns": "isb-operations",
  "kind": "Universal Islamic banking operations & compliance",
  "cases": [
   "Maintain AAOIFI Ledger Posting records consistently across the Islamic estate",
   "Combine conventional KYC/AML with Shariah-specific screening at onboarding",
   "Produce AAOIFI-basis financials and IFSB regulatory returns",
   "Operate branch/digital channels with products labeled by underlying contract"
  ],
  "providers": [
   "AML/screening: NICE Actimize, World-Check (plus Shariah screening data)",
   "Accounting: AAOIFI FAS-aligned GL mappings on SAP/Oracle",
   "Regulators: IFSB-aligned returns; national central banks"
  ]
 },
 {
  "name": "IFSB Regulatory Reporting",
  "repo": "isb-ifsb-regulatory-reporting",
  "deep": false,
  "area": "Takaful and Shared Operations",
  "domain": "Shared Operations",
  "pattern": "Process",
  "asset": "IFSB Regulatory Report",
  "cr": "IFSB Regulatory Report Procedure",
  "ns": "isb-operations",
  "kind": "Universal Islamic banking operations & compliance",
  "cases": [
   "Maintain IFSB Regulatory Report records consistently across the Islamic estate",
   "Combine conventional KYC/AML with Shariah-specific screening at onboarding",
   "Produce AAOIFI-basis financials and IFSB regulatory returns",
   "Operate branch/digital channels with products labeled by underlying contract"
  ],
  "providers": [
   "AML/screening: NICE Actimize, World-Check (plus Shariah screening data)",
   "Accounting: AAOIFI FAS-aligned GL mappings on SAP/Oracle",
   "Regulators: IFSB-aligned returns; national central banks"
  ]
 },
 {
  "name": "Branch And Digital Channel Operation",
  "repo": "isb-branch-and-digital-channel-operation",
  "deep": false,
  "area": "Takaful and Shared Operations",
  "domain": "Shared Operations",
  "pattern": "Operate",
  "asset": "Channel Session",
  "cr": "Channel Session Operating Session",
  "ns": "isb-operations",
  "kind": "Universal Islamic banking operations & compliance",
  "cases": [
   "Maintain Channel Session records consistently across the Islamic estate",
   "Combine conventional KYC/AML with Shariah-specific screening at onboarding",
   "Produce AAOIFI-basis financials and IFSB regulatory returns",
   "Operate branch/digital channels with products labeled by underlying contract"
  ],
  "providers": [
   "AML/screening: NICE Actimize, World-Check (plus Shariah screening data)",
   "Accounting: AAOIFI FAS-aligned GL mappings on SAP/Oracle",
   "Regulators: IFSB-aligned returns; national central banks"
  ]
 }
];
