// Generated from islamic-banking-services/registry.json — do not hand-edit.
const GH_OWNER = 'Sreenivas-Sadhu-Prabhakara';
const REGISTRY = [
 {
  "repo": "isb-shariah-supervisory-board-directory",
  "serviceDomain": "Shariah Supervisory Board Directory",
  "businessArea": "Shariah Governance and Compliance",
  "businessDomain": "Shariah Governance",
  "functionalPattern": "Catalog",
  "assetType": "SSB Member Mandate",
  "controlRecord": "SSB Member Mandate Directory Entry",
  "namespace": "isb-governance",
  "package": "com.bank.islamic.shariahsupervisoryboarddirectory"
 },
 {
  "repo": "isb-fatwa-and-ruling-repository",
  "serviceDomain": "Fatwa And Ruling Repository",
  "businessArea": "Shariah Governance and Compliance",
  "businessDomain": "Shariah Governance",
  "functionalPattern": "Catalog",
  "assetType": "Shariah Ruling",
  "controlRecord": "Shariah Ruling Directory Entry",
  "namespace": "isb-governance",
  "package": "com.bank.islamic.fatwaandrulingrepository"
 },
 {
  "repo": "isb-shariah-compliance-review",
  "serviceDomain": "Shariah Compliance Review",
  "businessArea": "Shariah Governance and Compliance",
  "businessDomain": "Shariah Governance",
  "functionalPattern": "Assess",
  "assetType": "Shariah Compliance Case",
  "controlRecord": "Shariah Compliance Case Assessment",
  "namespace": "isb-governance",
  "package": "com.bank.islamic.shariahcompliancereview"
 },
 {
  "repo": "isb-shariah-audit",
  "serviceDomain": "Shariah Audit",
  "businessArea": "Shariah Governance and Compliance",
  "businessDomain": "Shariah Governance",
  "functionalPattern": "Assess",
  "assetType": "Shariah Audit Engagement",
  "controlRecord": "Shariah Audit Engagement Assessment",
  "namespace": "isb-governance",
  "package": "com.bank.islamic.shariahaudit"
 },
 {
  "repo": "isb-income-purification",
  "serviceDomain": "Income Purification",
  "businessArea": "Shariah Governance and Compliance",
  "businessDomain": "Shariah Governance",
  "functionalPattern": "Process",
  "assetType": "Purification Entry",
  "controlRecord": "Purification Entry Procedure",
  "namespace": "isb-governance",
  "package": "com.bank.islamic.incomepurification"
 },
 {
  "repo": "isb-zakat-calculation",
  "serviceDomain": "Zakat Calculation",
  "businessArea": "Shariah Governance and Compliance",
  "businessDomain": "Shariah Governance",
  "functionalPattern": "Process",
  "assetType": "Zakat Assessment",
  "controlRecord": "Zakat Assessment Procedure",
  "namespace": "isb-governance",
  "package": "com.bank.islamic.zakatcalculation"
 },
 {
  "repo": "isb-zakat-distribution",
  "serviceDomain": "Zakat Distribution",
  "businessArea": "Shariah Governance and Compliance",
  "businessDomain": "Shariah Governance",
  "functionalPattern": "Distribute",
  "assetType": "Zakat Disbursement",
  "controlRecord": "Zakat Disbursement Distribution",
  "namespace": "isb-governance",
  "package": "com.bank.islamic.zakatdistribution"
 },
 {
  "repo": "isb-sadaqah-and-charity-management",
  "serviceDomain": "Sadaqah And Charity Management",
  "businessArea": "Shariah Governance and Compliance",
  "businessDomain": "Shariah Governance",
  "functionalPattern": "Manage",
  "assetType": "Charity Pool",
  "controlRecord": "Charity Pool Management Plan",
  "namespace": "isb-governance",
  "package": "com.bank.islamic.sadaqahandcharitymanagement"
 },
 {
  "repo": "isb-wadiah-safekeeping-account",
  "serviceDomain": "Wadiah Safekeeping Account",
  "businessArea": "Deposits and Investment Accounts",
  "businessDomain": "Islamic Deposits",
  "functionalPattern": "Fulfill",
  "assetType": "Wadiah Custody Account",
  "controlRecord": "Wadiah Custody Account Fulfillment Arrangement",
  "namespace": "isb-deposits",
  "package": "com.bank.islamic.wadiahsafekeepingaccount"
 },
 {
  "repo": "isb-qard-hassan-account",
  "serviceDomain": "Qard Hassan Account",
  "businessArea": "Deposits and Investment Accounts",
  "businessDomain": "Islamic Deposits",
  "functionalPattern": "Fulfill",
  "assetType": "Qard Hassan Account",
  "controlRecord": "Qard Hassan Account Fulfillment Arrangement",
  "namespace": "isb-deposits",
  "package": "com.bank.islamic.qardhassanaccount"
 },
 {
  "repo": "isb-mudarabah-savings-account",
  "serviceDomain": "Mudarabah Savings Account",
  "businessArea": "Deposits and Investment Accounts",
  "businessDomain": "Islamic Deposits",
  "functionalPattern": "Fulfill",
  "assetType": "Mudarabah Savings Account",
  "controlRecord": "Mudarabah Savings Account Fulfillment Arrangement",
  "namespace": "isb-deposits",
  "package": "com.bank.islamic.mudarabahsavingsaccount"
 },
 {
  "repo": "isb-mudarabah-term-investment-account",
  "serviceDomain": "Mudarabah Term Investment Account",
  "businessArea": "Deposits and Investment Accounts",
  "businessDomain": "Islamic Deposits",
  "functionalPattern": "Fulfill",
  "assetType": "Mudarabah Investment Account",
  "controlRecord": "Mudarabah Investment Account Fulfillment Arrangement",
  "namespace": "isb-deposits",
  "package": "com.bank.islamic.mudarabahterminvestmentaccount"
 },
 {
  "repo": "isb-wakala-investment-account",
  "serviceDomain": "Wakala Investment Account",
  "businessArea": "Deposits and Investment Accounts",
  "businessDomain": "Islamic Deposits",
  "functionalPattern": "Fulfill",
  "assetType": "Wakala Investment Account",
  "controlRecord": "Wakala Investment Account Fulfillment Arrangement",
  "namespace": "isb-deposits",
  "package": "com.bank.islamic.wakalainvestmentaccount"
 },
 {
  "repo": "isb-profit-calculation-and-distribution",
  "serviceDomain": "Profit Calculation And Distribution",
  "businessArea": "Deposits and Investment Accounts",
  "businessDomain": "Profit Management",
  "functionalPattern": "Process",
  "assetType": "Profit Distribution Run",
  "controlRecord": "Profit Distribution Run Procedure",
  "namespace": "isb-deposits",
  "package": "com.bank.islamic.profitcalculationanddistribution"
 },
 {
  "repo": "isb-profit-equalization-reserve",
  "serviceDomain": "Profit Equalization Reserve",
  "businessArea": "Deposits and Investment Accounts",
  "businessDomain": "Profit Management",
  "functionalPattern": "Manage",
  "assetType": "Profit Equalization Reserve",
  "controlRecord": "Profit Equalization Reserve Management Plan",
  "namespace": "isb-deposits",
  "package": "com.bank.islamic.profitequalizationreserve"
 },
 {
  "repo": "isb-investment-risk-reserve",
  "serviceDomain": "Investment Risk Reserve",
  "businessArea": "Deposits and Investment Accounts",
  "businessDomain": "Profit Management",
  "functionalPattern": "Manage",
  "assetType": "Investment Risk Reserve",
  "controlRecord": "Investment Risk Reserve Management Plan",
  "namespace": "isb-deposits",
  "package": "com.bank.islamic.investmentriskreserve"
 },
 {
  "repo": "isb-hibah-discretionary-gift",
  "serviceDomain": "Hibah Discretionary Gift",
  "businessArea": "Deposits and Investment Accounts",
  "businessDomain": "Profit Management",
  "functionalPattern": "Process",
  "assetType": "Hibah Award",
  "controlRecord": "Hibah Award Procedure",
  "namespace": "isb-deposits",
  "package": "com.bank.islamic.hibahdiscretionarygift"
 },
 {
  "repo": "isb-murabaha-financing",
  "serviceDomain": "Murabaha Financing",
  "businessArea": "Islamic Financing",
  "businessDomain": "Sale Based Financing",
  "functionalPattern": "Fulfill",
  "assetType": "Murabaha Facility",
  "controlRecord": "Murabaha Facility Fulfillment Arrangement",
  "namespace": "isb-financing",
  "package": "com.bank.islamic.murabahafinancing"
 },
 {
  "repo": "isb-commodity-murabaha-tawarruq",
  "serviceDomain": "Commodity Murabaha Tawarruq",
  "businessArea": "Islamic Financing",
  "businessDomain": "Sale Based Financing",
  "functionalPattern": "Process",
  "assetType": "Tawarruq Transaction",
  "controlRecord": "Tawarruq Transaction Procedure",
  "namespace": "isb-financing",
  "package": "com.bank.islamic.commoditymurabahatawarruq"
 },
 {
  "repo": "isb-istisna-construction-financing",
  "serviceDomain": "Istisna Construction Financing",
  "businessArea": "Islamic Financing",
  "businessDomain": "Sale Based Financing",
  "functionalPattern": "Fulfill",
  "assetType": "Istisna Facility",
  "controlRecord": "Istisna Facility Fulfillment Arrangement",
  "namespace": "isb-financing",
  "package": "com.bank.islamic.istisnaconstructionfinancing"
 },
 {
  "repo": "isb-salam-commodity-forward",
  "serviceDomain": "Salam Commodity Forward",
  "businessArea": "Islamic Financing",
  "businessDomain": "Sale Based Financing",
  "functionalPattern": "Fulfill",
  "assetType": "Salam Contract",
  "controlRecord": "Salam Contract Fulfillment Arrangement",
  "namespace": "isb-financing",
  "package": "com.bank.islamic.salamcommodityforward"
 },
 {
  "repo": "isb-asset-acquisition-agency",
  "serviceDomain": "Asset Acquisition Agency",
  "businessArea": "Islamic Financing",
  "businessDomain": "Sale Based Financing",
  "functionalPattern": "Process",
  "assetType": "Wakala Purchase Mandate",
  "controlRecord": "Wakala Purchase Mandate Procedure",
  "namespace": "isb-financing",
  "package": "com.bank.islamic.assetacquisitionagency"
 },
 {
  "repo": "isb-ijara-leasing",
  "serviceDomain": "Ijara Leasing",
  "businessArea": "Islamic Financing",
  "businessDomain": "Lease And Partnership Financing",
  "functionalPattern": "Fulfill",
  "assetType": "Ijara Lease",
  "controlRecord": "Ijara Lease Fulfillment Arrangement",
  "namespace": "isb-financing",
  "package": "com.bank.islamic.ijaraleasing"
 },
 {
  "repo": "isb-ijara-muntahia-bittamleek",
  "serviceDomain": "Ijara Muntahia Bittamleek",
  "businessArea": "Islamic Financing",
  "businessDomain": "Lease And Partnership Financing",
  "functionalPattern": "Fulfill",
  "assetType": "Lease To Own Arrangement",
  "controlRecord": "Lease To Own Arrangement Fulfillment Arrangement",
  "namespace": "isb-financing",
  "package": "com.bank.islamic.ijaramuntahiabittamleek"
 },
 {
  "repo": "isb-diminishing-musharakah-home-finance",
  "serviceDomain": "Diminishing Musharakah Home Finance",
  "businessArea": "Islamic Financing",
  "businessDomain": "Lease And Partnership Financing",
  "functionalPattern": "Fulfill",
  "assetType": "Diminishing Musharakah Facility",
  "controlRecord": "Diminishing Musharakah Facility Fulfillment Arrangement",
  "namespace": "isb-financing",
  "package": "com.bank.islamic.diminishingmusharakahhomefinance"
 },
 {
  "repo": "isb-musharakah-partnership-financing",
  "serviceDomain": "Musharakah Partnership Financing",
  "businessArea": "Islamic Financing",
  "businessDomain": "Lease And Partnership Financing",
  "functionalPattern": "Fulfill",
  "assetType": "Musharakah Facility",
  "controlRecord": "Musharakah Facility Fulfillment Arrangement",
  "namespace": "isb-financing",
  "package": "com.bank.islamic.musharakahpartnershipfinancing"
 },
 {
  "repo": "isb-mudarabah-venture-financing",
  "serviceDomain": "Mudarabah Venture Financing",
  "businessArea": "Islamic Financing",
  "businessDomain": "Lease And Partnership Financing",
  "functionalPattern": "Fulfill",
  "assetType": "Mudarabah Facility",
  "controlRecord": "Mudarabah Facility Fulfillment Arrangement",
  "namespace": "isb-financing",
  "package": "com.bank.islamic.mudarabahventurefinancing"
 },
 {
  "repo": "isb-qard-hassan-benevolent-loan",
  "serviceDomain": "Qard Hassan Benevolent Loan",
  "businessArea": "Islamic Financing",
  "businessDomain": "Lease And Partnership Financing",
  "functionalPattern": "Fulfill",
  "assetType": "Qard Hassan Facility",
  "controlRecord": "Qard Hassan Facility Fulfillment Arrangement",
  "namespace": "isb-financing",
  "package": "com.bank.islamic.qardhassanbenevolentloan"
 },
 {
  "repo": "isb-late-payment-charity-handling",
  "serviceDomain": "Late Payment Charity Handling",
  "businessArea": "Islamic Financing",
  "businessDomain": "Lease And Partnership Financing",
  "functionalPattern": "Process",
  "assetType": "Late Payment Charity Entry",
  "controlRecord": "Late Payment Charity Entry Procedure",
  "namespace": "isb-financing",
  "package": "com.bank.islamic.latepaymentcharityhandling"
 },
 {
  "repo": "isb-sukuk-issuance",
  "serviceDomain": "Sukuk Issuance",
  "businessArea": "Treasury Markets and Sukuk",
  "businessDomain": "Sukuk",
  "functionalPattern": "Process",
  "assetType": "Sukuk Issuance Program",
  "controlRecord": "Sukuk Issuance Program Procedure",
  "namespace": "isb-treasury",
  "package": "com.bank.islamic.sukukissuance"
 },
 {
  "repo": "isb-sukuk-registry-and-custody",
  "serviceDomain": "Sukuk Registry And Custody",
  "businessArea": "Treasury Markets and Sukuk",
  "businessDomain": "Sukuk",
  "functionalPattern": "Administer",
  "assetType": "Sukuk Holding",
  "controlRecord": "Sukuk Holding Administrative Plan",
  "namespace": "isb-treasury",
  "package": "com.bank.islamic.sukukregistryandcustody"
 },
 {
  "repo": "isb-sukuk-portfolio-management",
  "serviceDomain": "Sukuk Portfolio Management",
  "businessArea": "Treasury Markets and Sukuk",
  "businessDomain": "Sukuk",
  "functionalPattern": "Manage",
  "assetType": "Sukuk Portfolio",
  "controlRecord": "Sukuk Portfolio Management Plan",
  "namespace": "isb-treasury",
  "package": "com.bank.islamic.sukukportfoliomanagement"
 },
 {
  "repo": "isb-interbank-commodity-murabaha-desk",
  "serviceDomain": "Interbank Commodity Murabaha Desk",
  "businessArea": "Treasury Markets and Sukuk",
  "businessDomain": "Islamic Treasury",
  "functionalPattern": "Operate",
  "assetType": "Interbank Murabaha Deal",
  "controlRecord": "Interbank Murabaha Deal Operating Session",
  "namespace": "isb-treasury",
  "package": "com.bank.islamic.interbankcommoditymurabahadesk"
 },
 {
  "repo": "isb-islamic-fx-wad-arrangements",
  "serviceDomain": "Islamic FX Wad Arrangements",
  "businessArea": "Treasury Markets and Sukuk",
  "businessDomain": "Islamic Treasury",
  "functionalPattern": "Process",
  "assetType": "Wad FX Arrangement",
  "controlRecord": "Wad FX Arrangement Procedure",
  "namespace": "isb-treasury",
  "package": "com.bank.islamic.islamicfxwadarrangements"
 },
 {
  "repo": "isb-shariah-compliant-liquidity-management",
  "serviceDomain": "Shariah Compliant Liquidity Management",
  "businessArea": "Treasury Markets and Sukuk",
  "businessDomain": "Islamic Treasury",
  "functionalPattern": "Manage",
  "assetType": "Liquidity Position",
  "controlRecord": "Liquidity Position Management Plan",
  "namespace": "isb-treasury",
  "package": "com.bank.islamic.shariahcompliantliquiditymanagement"
 },
 {
  "repo": "isb-halal-equity-screening",
  "serviceDomain": "Halal Equity Screening",
  "businessArea": "Treasury Markets and Sukuk",
  "businessDomain": "Islamic Treasury",
  "functionalPattern": "Assess",
  "assetType": "Equity Screening Result",
  "controlRecord": "Equity Screening Result Assessment",
  "namespace": "isb-treasury",
  "package": "com.bank.islamic.halalequityscreening"
 },
 {
  "repo": "isb-takaful-policy-administration",
  "serviceDomain": "Takaful Policy Administration",
  "businessArea": "Takaful and Shared Operations",
  "businessDomain": "Takaful",
  "functionalPattern": "Administer",
  "assetType": "Takaful Certificate",
  "controlRecord": "Takaful Certificate Administrative Plan",
  "namespace": "isb-operations",
  "package": "com.bank.islamic.takafulpolicyadministration"
 },
 {
  "repo": "isb-takaful-claims-processing",
  "serviceDomain": "Takaful Claims Processing",
  "businessArea": "Takaful and Shared Operations",
  "businessDomain": "Takaful",
  "functionalPattern": "Process",
  "assetType": "Takaful Claim",
  "controlRecord": "Takaful Claim Procedure",
  "namespace": "isb-operations",
  "package": "com.bank.islamic.takafulclaimsprocessing"
 },
 {
  "repo": "isb-retakaful-arrangement",
  "serviceDomain": "Retakaful Arrangement",
  "businessArea": "Takaful and Shared Operations",
  "businessDomain": "Takaful",
  "functionalPattern": "Manage",
  "assetType": "Retakaful Treaty",
  "controlRecord": "Retakaful Treaty Management Plan",
  "namespace": "isb-operations",
  "package": "com.bank.islamic.retakafularrangement"
 },
 {
  "repo": "isb-ujrah-card-services",
  "serviceDomain": "Ujrah Card Services",
  "businessArea": "Takaful and Shared Operations",
  "businessDomain": "Islamic Cards and Payments",
  "functionalPattern": "Fulfill",
  "assetType": "Ujrah Card Facility",
  "controlRecord": "Ujrah Card Facility Fulfillment Arrangement",
  "namespace": "isb-operations",
  "package": "com.bank.islamic.ujrahcardservices"
 },
 {
  "repo": "isb-payment-order",
  "serviceDomain": "Payment Order",
  "businessArea": "Takaful and Shared Operations",
  "businessDomain": "Islamic Cards and Payments",
  "functionalPattern": "Process",
  "assetType": "Payment Order",
  "controlRecord": "Payment Order Procedure",
  "namespace": "isb-operations",
  "package": "com.bank.islamic.paymentorder"
 },
 {
  "repo": "isb-payment-execution",
  "serviceDomain": "Payment Execution",
  "businessArea": "Takaful and Shared Operations",
  "businessDomain": "Islamic Cards and Payments",
  "functionalPattern": "Process",
  "assetType": "Payment Transaction",
  "controlRecord": "Payment Transaction Procedure",
  "namespace": "isb-operations",
  "package": "com.bank.islamic.paymentexecution"
 },
 {
  "repo": "isb-customer-reference-data",
  "serviceDomain": "Customer Reference Data",
  "businessArea": "Takaful and Shared Operations",
  "businessDomain": "Shared Operations",
  "functionalPattern": "Maintain",
  "assetType": "Customer Reference Data",
  "controlRecord": "Customer Reference Data Maintenance Agreement",
  "namespace": "isb-operations",
  "package": "com.bank.islamic.customerreferencedata"
 },
 {
  "repo": "isb-kyc-and-shariah-screening",
  "serviceDomain": "KYC And Shariah Screening",
  "businessArea": "Takaful and Shared Operations",
  "businessDomain": "Shared Operations",
  "functionalPattern": "Process",
  "assetType": "KYC Shariah Assessment",
  "controlRecord": "KYC Shariah Assessment Procedure",
  "namespace": "isb-operations",
  "package": "com.bank.islamic.kycandshariahscreening"
 },
 {
  "repo": "isb-financial-crime-monitoring",
  "serviceDomain": "Financial Crime Monitoring",
  "businessArea": "Takaful and Shared Operations",
  "businessDomain": "Shared Operations",
  "functionalPattern": "Monitor",
  "assetType": "Financial Crime Alert",
  "controlRecord": "Financial Crime Alert Monitoring State",
  "namespace": "isb-operations",
  "package": "com.bank.islamic.financialcrimemonitoring"
 },
 {
  "repo": "isb-aaoifi-financial-accounting",
  "serviceDomain": "AAOIFI Financial Accounting",
  "businessArea": "Takaful and Shared Operations",
  "businessDomain": "Shared Operations",
  "functionalPattern": "Process",
  "assetType": "AAOIFI Ledger Posting",
  "controlRecord": "AAOIFI Ledger Posting Procedure",
  "namespace": "isb-operations",
  "package": "com.bank.islamic.aaoififinancialaccounting"
 },
 {
  "repo": "isb-ifsb-regulatory-reporting",
  "serviceDomain": "IFSB Regulatory Reporting",
  "businessArea": "Takaful and Shared Operations",
  "businessDomain": "Shared Operations",
  "functionalPattern": "Process",
  "assetType": "IFSB Regulatory Report",
  "controlRecord": "IFSB Regulatory Report Procedure",
  "namespace": "isb-operations",
  "package": "com.bank.islamic.ifsbregulatoryreporting"
 },
 {
  "repo": "isb-branch-and-digital-channel-operation",
  "serviceDomain": "Branch And Digital Channel Operation",
  "businessArea": "Takaful and Shared Operations",
  "businessDomain": "Shared Operations",
  "functionalPattern": "Operate",
  "assetType": "Channel Session",
  "controlRecord": "Channel Session Operating Session",
  "namespace": "isb-operations",
  "package": "com.bank.islamic.branchanddigitalchanneloperation"
 }
];
