package __PACKAGE__;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: __SD_NAME__
 *
 * Business Area:      __BUSINESS_AREA__
 * Business Domain:    __BUSINESS_DOMAIN__
 * Functional Pattern: __FUNCTIONAL_PATTERN__
 * Asset Type:         __ASSET_TYPE__
 * Control Record:     __CONTROL_RECORD__
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("__SD_NAME__ — BIAN Semantic API")
                .description("Service Domain '__SD_NAME__' (__FUNCTIONAL_PATTERN__ pattern) "
                        + "operating on the '__CONTROL_RECORD__' control record.")
                .version("0.1.0"));
    }
}
